# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOVERSION: 1.12

steps:
  - task: GoTool@0
    displayName: 'Use Go $(GOVERSION)'
    inputs:
      version: $(GOVERSION)
  - task: Go@0
    inputs:
      command: test
      arguments: -v ./...
    displayName: 'Execute Tests'
